### ISSUE TITLE
Adjusting the timestamp in combineNSxNEV

### ISSUE THREAD

**Issue by ferchaure** [BlackrockMicrosystems/NPMK#6]
Hi, I found very intriguing lines in combineNSxNEV. For example line 81:
`NEV2.Data.Comments.TimeStampSec = NEV2.Data.Comments.TimeStampSec + double(NSx1DataLength)/30;`

I think that the correct way to calculate the length in seconds of NSx1, is: `double(NSx1DataLength)/30000` or better: `double(NSx1DataLength)/NSx1.MetaTags.SamplingFreq`

Am I right or terrible confused?

**Comment by NHalper** [comment]
Ferchaure, 

An NS1 is sampled at 500 s/s, so it would be correct to divide the data by 500 to translate samples into seconds. An NEV is sampled at 30000 s/s so it is appropriate to divide those by 30000. 

You can see above the Kian does some modification of the meaning of NSx1DataLength so that dividing it by 30000 would be appropriate again. 

We will put this in for correction. 

Nick

**Comment by kianabc** [comment]
This is fxied. Thanks for reporting this, Fernando.

**Comment by ferchaure** [comment]
Where can I find the fixed code?
